{% set name = "google-java-format" %}
{% set version = "1.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 85d47984a145fce834da8f22247b039a85cac6b542893949e5d3737e3707f5fe

build:
  noarch: generic
  number: 0

requirements:
  build:
    - maven
    - openjdk =17
  run:
    - openjdk
    - python

test:
  commands:
    - google-java-format --help 2>&1 | grep -q "google\-java\-format"
    - google-java-format-diff --help

about:
  home: https://github.com/google/google-java-format
  license: Apache-2.0
  license_file:
    - LICENSE
    - target/generated-resources/licenses/
  summary: Reformats Java source code to comply with Google Java Style

extra:
  recipe-maintainers:
    - danielnachun
