context:
  version: "1.35.0"

package:
  name: google-java-format
  version: ${{ version }}

source:
  url: https://github.com/google/google-java-format/archive/v${{ version }}.tar.gz
  sha256: cae14f13a52b1f11052f1189b3bc71615c4b5ae3e34e4f64e4732eab079586c8

build:
  number: 0
  noarch: generic

requirements:
  build:
    - maven
    - openjdk
  run:
    - openjdk
    - python

tests:
  - script:
      - "google-java-format --help 2>&1 | grep -q \"google\\-java\\-format\""
      - google-java-format-diff --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - target/generated-resources/licenses/
  summary: Reformats Java source code to comply with Google Java Style
  homepage: https://github.com/google/google-java-format

extra:
  recipe-maintainers:
    - danielnachun
