context:
  version: "1.25.2"

package:
  name: google-java-format
  version: ${{ version }}

source:
  url: https://github.com/google/google-java-format/archive/v${{ version }}.tar.gz
  sha256: d1ec0eff87886b8dbe7f563b2e5c03e477ee1951b525c4b909698cab8beeee75

build:
  number: 0
  noarch: generic

requirements:
  build:
    - maven
    - openjdk =17
  run:
    - openjdk
    - python

tests:
  - script:
      - "google-java-format --help 2>&1 | grep -q \"google\\-java\\-format\""
      - google-java-format-diff --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - target/generated-resources/licenses/
  summary: Reformats Java source code to comply with Google Java Style
  homepage: https://github.com/google/google-java-format

extra:
  recipe-maintainers:
    - danielnachun
