context:
  version: "1.37.0"

package:
  name: google-java-format
  version: ${{ version }}

source:
  url: https://github.com/google/google-java-format/archive/v${{ version }}.tar.gz
  sha256: 4cea7317fdc66f936c485a7ba964ca24d4e90c1cdc9f14fcb4c0e3e33e432442

build:
  number: 0
  noarch: generic

requirements:
  build:
    - maven
    - openjdk
  run:
    - openjdk
    - python

tests:
  - script:
      - "google-java-format --help 2>&1 | grep -q \"google\\-java\\-format\""
      - google-java-format-diff --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - target/generated-resources/licenses/
  summary: Reformats Java source code to comply with Google Java Style
  homepage: https://github.com/google/google-java-format

extra:
  recipe-maintainers:
    - danielnachun
