context:
  version: "1.36.0"

package:
  name: google-java-format
  version: ${{ version }}

source:
  url: https://github.com/google/google-java-format/archive/v${{ version }}.tar.gz
  sha256: d310988c5a73ca130109f9cd51253959fd1fb31e9283f9fd531123963d4e1268

build:
  number: 0
  noarch: generic

requirements:
  build:
    - maven
    - openjdk
  run:
    - openjdk
    - python

tests:
  - script:
      - "google-java-format --help 2>&1 | grep -q \"google\\-java\\-format\""
      - google-java-format-diff --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - target/generated-resources/licenses/
  summary: Reformats Java source code to comply with Google Java Style
  homepage: https://github.com/google/google-java-format

extra:
  recipe-maintainers:
    - danielnachun
