context:
  version: "1.30.0"

package:
  name: google-java-format
  version: ${{ version }}

source:
  url: https://github.com/google/google-java-format/archive/v${{ version }}.tar.gz
  sha256: 8141f8b93b6c514a3f466497e1bad652bd0da7d4bb2a477511a73ca23e9c59d0

build:
  number: 0
  noarch: generic

requirements:
  build:
    - maven
    - openjdk =17
  run:
    - openjdk
    - python

tests:
  - script:
      - "google-java-format --help 2>&1 | grep -q \"google\\-java\\-format\""
      - google-java-format-diff --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - target/generated-resources/licenses/
  summary: Reformats Java source code to comply with Google Java Style
  homepage: https://github.com/google/google-java-format

extra:
  recipe-maintainers:
    - danielnachun
